name: unit_test

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    runs-on: windows

    steps:

      - name: Jenkins-Action
        uses: joshlk/jenkins-githubaction@V0.0.1

      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.18
      - name: Install Dependencies
        run: npm ci
      - name: Run tests
        run: npm tests